### ISSUE TITLE
Debug software boot issue on EM002

### ISSUE THREAD

**Issue by tiwari3101** [infiniteorbits/hart-software-services#5] opened 2024-06-20 11:57 UTC
With this version of the HSS(even without custom modifications), the software payload does not boot. Investigation is needed.

**Comment by abelixrev** [comment] 2024-07-09 07:14
The same behavior is observed with the following versions of HSS:
- 0.99.33
- 0.99.33 with custom slot selection feature
- 2024.06

The issue is that many times the payload successfully passes the HSS checks (CRC, Header name, magic number), but when it jumps to the first position of the DDR to start the payload, it does not execute.

Traces have been added at different memory positions in the DDR to verify that the data copy from the EMMC is done correctly, and these data have been compared with the payload binary in hexadecimal format with positive results.

The issue is on hold until the meeting on Thursday, 11/07, when the contact from Microchip will advise us on the next steps.

**Comment by abelixrev** [comment] 2024-07-29 12:20
The issue described in this ticket has been resolved with the updates made in [ticket #4](https://github.com/infiniteorbits/hart-software-services/issues/4).

Therefore, we are closing this ticket: Debug software boot issue on EM002 #5.

**Closed by abelixrev** 2024-07-29 12:20 UTC
